### ISSUE TITLE
Is the multi-threaded version deterministic?

### ISSUE THREAD

**Issue by fdecarpentier** [fmenardo/Treemmer#10]
Hi Fernando,

Thank you for the great tool.
As Treemmer is an iterative process, I'm wondering if the multi-threaded version is deterministic? 
Could you elaborate on how the work is split between cores?

Thanks

**Comment by fmenardo** [comment]
Hi @fdecarpentier,
the only part of Treemmer that is parallelized is the identification of the neighbor (and distance calculation). This takes some time, and it can be done independently for each leaf, so it is good/easy to parallelize it. This produces a list of neighbor pairs  and distances, and the results are identical to the serial version. 
The decision about which leaf to prune (given the list of neighbor pairs  and distances) is not parallelized. So no it is not deterministic.
I hope this helps
Fabrizio

**Comment by fdecarpentier** [comment]
Thank you for your response. What I meant by deterministic is that the final result will be the same with a single or several threads. If I understood well, it is the case, so the program is deterministic (right?).

**Comment by fmenardo** [comment]
Ok, my answer was misleading.
At each iteration Treemmer identifies the closest neighbor for each leaf and calculates the distance. Then it takes the pair with the minimum distance and prunes one leaf. If there are multiple pairs with identical minimum distance, it takes one pair at random. In this case it is not deterministic. In absence of multiple pairs with minimum distance, Treemmer is deterministic.
Single and multi threads versions have the exact same behavior.
Let me know if it's clear

**Comment by fmenardo** [comment]
Hi @fdecarpentier 
My answer was maybe misleading,
In its default behavior Treemmer is not deterministic, because once identified the pair of leaves to prune one of the two is pruned at random. Therefore if you run twice Treemmer you will end up with different pruned trees. This does not depend on single vs multi threads. If you run twice the single thread version you may also get different results. 
Selecting single or multi threads does not change the behavior of Treemmer at all, it only makes it faster.

Let me know if this answer you question

**Comment by fdecarpentier** [comment]
Okay, I see. Thank you for the clarification. So, if I prune the shortest (or longest) leave at each round, it's deterministic.

**Comment by fmenardo** [comment]
Yes, unless there are multiple pairs of leaves with identical min distance, in such case the pair to prune is chosen at random among those, and it is not deterministic anymore.
Depending on the type of tree / field you are working in, this can be very common
